[package]
name = "rusty-games-library"
version = "0.1.0"
authors = ["Tomek Karwowski <to.karwowski@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde-json-wasm = "0.3"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
log = "0.4"
wasm-logger = "0.2"
wasm-bindgen-test = "0.3"

rusty-games-protocol = {path = "../protocol"}

[dependencies.web-sys]
version = "0.3.22"
features = [
    "console",

    # random SessionID generation
    "Window",
    "Crypto",

    # WebRTC features
    "MessageEvent",
    "RtcPeerConnection",
    "RtcSignalingState",
    "RtcSdpType",
    "RtcSessionDescriptionInit",
    "RtcPeerConnectionIceEvent",
    "RtcIceConnectionState",
    "RtcIceCandidate",
    "RtcIceCandidateInit",
    "RtcDataChannel",
    "RtcDataChannelEvent",
    "RtcConfiguration",
    "RtcIceGatheringState",

    # WebSocket features
    "WebSocket",
    "BinaryType",
]