name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cd signaling-server && cargo run &
      - run: cd library && WS_IP_PORT=127.0.0.1:9001 wasm-pack test --headless --firefox
      - run: cd library && WS_IP_PORT=127.0.0.1:9001 wasm-pack test --headless --chrome
