name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo run &
        working-directory: ./signaling-server
      - run: wasm-pack test --headless --firefox
        working-directory: ./library
        env:
          WS_IP_PORT: 127.0.0.1:9001
      - run: wasm-pack test --headless --chrome
        working-directory: ./library
        env:
          WS_IP_PORT: 127.0.0.1:9001
